## [특강] Numpy, Pandas, Matplotlib

### 1. Numpy: 고속 연산, 슬라이싱 및 차원 제어
#### 1.1 명시적 타입 배열 생성과 다차원 슬라이싱

배열(Array): 

파이썬 리스트:
힙 영역: 숫자 1에 대한 객체 또는 문자 abc라는 객체가 있을때, 주소값만 가지고 접근


배열(같은 자료형 - int, float)
- 메모리상 연속된 구조로 되어있음. 인덱스 연산자([]) 접근 가능
- 동일한 자료형으로 데이터가 구성
- C언어로 개발되어 있음. (직접 메모리 접근이 가능)


방의 크기
비트(bit) - 0과 1로 나타낼 수 있음.
바이트(byte) - 비트 * 8, 1 byte = 8 bits (-256 ~ 255까지의 숫자를 표현함)
 - 바이트의 첫 비트는 음수와 양수로 표현되는 부호 비트임.



In [1]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\csong\ax_study\04_MACHINE_LEARNING\.venv-1\Scripts\python.exe
3.13.14 (main, Aug  5 2026, 16:10:10) [MSC v.1944 64 bit (AMD64)]


In [8]:
import numpy as np

nums = np.array([10,20,30], dtype=np.float64)  #  1차원 배열(Vector)
nums


array([10., 20., 30.])

In [4]:
nums[1]

np.int64(20)

In [7]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]]) #  2차원 배열(Matrix)

# 참고로 3차원 이상의 배열(Tensor)이라고 말합니다.
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

#### 배열 선택, 슬라이싱
- matrix[행, 열]
- matrix[0:2, 1:3] : 행은 0, 1, 열은 1, 2

print("0행 2열:", matrix[0][2], matrix[0,2])


In [ ]:
print("0행과 2열:", matrix[0][2], matrix[0,2])
print(matrix[0:2, 1:3])

matrix[:,0] -> 모든 행의 0번째 열
matrix[1:, :2] -> 행은 1번 인덱스부터 전체, 열은 1번 인덱스 이하


0행과 2열: 30 30
[[20 30]
 [50 60]]


In [11]:
print(matrix[:, 0])
print(matrix[1:, :2])

[10 40 70]
[[40 50]
 [70 80]]


#### 1.2 차원 변경(reshape, flatten)과 축(Axis)

reshape(행, 열) / flatten()

In [ ]:
- reshape(행, 열) - 1차원 배열 -> 지정된 행과 열 구조로 차원수를 변경
- arange(시작, 종료, 증감단위) -> 시작 이상 종료 미반으로 숫자를 생성
- flatten() - 2차원 배열 --> 1차원으로 평탄화

In [17]:
arr = np.arange(1,13) # 1 ~ 12
mat_3X4 = arr.reshape(3,4)
print(mat_3X4)

flat_arr = mat_3X4.flatten()
print(flat_arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


축(axis)

2차원 배열에서 연산의 방행을 설정
- axis: 0 -> 행기준에서 연산
- axis: 1 -> 열기준에서 연산

In [21]:
mat = np.arange(1, 7).reshape(2,-1)

print(mat)

sum_axis0=mat.sum(axis=0)

sum_axis1=mat.sum(axis=1)

print("행 기준 합계:", sum_axis0)

print("열 기준 합계:", sum_axis1)

[[1 2 3]
 [4 5 6]]
행 기준 합계: [5 7 9]
열 기준 합계: [ 6 15]


In [19]:
mat = np.arange(1,7).reshape(2,-1)
mat


array([[1, 2, 3],
       [4, 5, 6]])

#### 1.3 Numpy 브로드캐스팅(Broadcasting) 연산

In [22]:
mat = np.array([
    [10,20,30],
    [40,50,60]
])

In [23]:
mat * 5

array([[ 50, 100, 150],
       [200, 250, 300]])

In [ ]:
vec = np.array([1,2,3])
mat + vec



array([[11, 22, 33],
       [41, 52, 63]])

#### 1.4 행렬 전치(Transpose) 및 행렬곱(@)

In [ ]:
객체.transpose() -> {행, 열} -> {열, 행} / 전치
 - 객체.T
 - 행렬 곱 연산(@)
 - 
 - 

In [27]:
mat = np.array([[1,2,3], [4,5,6]])

print(mat)
print("전치 행렬:\n", mat.transpose())
print('전치 행렬:\n', mat.T)

[[1 2 3]
 [4 5 6]]
전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]
전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]


In [31]:
mat1 = np.array([[10,20], [30,40]])
mat2 = np.array([[1,2], [4,5]])

mat3 = mat1 @ mat2

mat3


array([[ 90, 120],
       [190, 260]])